# Generated by Django 3.0.4 on 2020-05-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_auto_20200502_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='line_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='unit_price',
        ),
        migrations.AlterField(
            model_name='itemtopping',
            name='allowed_parents',
            field=models.ManyToManyField(to='eshop.Category'),
        ),
    ]
