# Generated by Django 3.0.2 on 2020-01-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_auto_20200107_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(default='small', max_length=16),
            preserve_default=False,
        ),
    ]
