# Generated by Django 3.0.2 on 2020-01-08 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('eshop', '0007_auto_20200108_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='size',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='allowed_parents',
        ),
        migrations.AlterField(
            model_name='detail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.Item'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='toppings',
            field=models.ManyToManyField(to='menu.Topping'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
