# Generated by Django 3.0.4 on 2020-05-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0007_auto_20200502_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtopping',
            name='allowed_category',
        ),
        migrations.AddField(
            model_name='itemtopping',
            name='allowed_categories',
            field=models.ManyToManyField(to='eshop.Category'),
        ),
    ]
