# Generated by Django 3.0.2 on 2020-01-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0008_auto_20200108_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(null=True),
        ),
    ]
