# Generated by Django 3.0.4 on 2020-05-23 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0009_orderline_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='toppings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eshop.MenuItem'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop.Order'),
        ),
    ]
